[package]
name = "boxoban-level-generator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
ndarray = "0.15.3"
fxhash = "0.2.1"
rayon = "1.5.1"
itertools = "0.10.1"